[project]
name = "head-pose-estimation-based-face-verification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "facenet-pytorch>=2.6.0",
    "fastapi[standard]>=0.115.11",
    "opencv-python>=4.11.0.86",
    "pyside6>=6.8.2.1",
    "scipy>=1.15.2",
]
